### ISSUE TITLE
Mod breaks multiblocks using vanilla lanterns

### ISSUE THREAD

**Issue by Tsuyurin** [SuperMartijn642/AdditionalLanterns#2]
Using Additional Lanterns 1.0.0-mc1.18:

Multi-block structures from other mods break if they include vanilla lanterns, because this mod changes lanterns to "Additional Lanterns" lanterns when placed.

Example: the Sanctum of Invocation structure from Mana and Artifice (using the ritual of the same name when aligned with the fae courts).

**Comment by SuperMartijn642** [comment]
Additional Lanterns replaces the vanilla lantern, but keeps it under the same `minecraft:lantern` registry name, so mods should still recognize the lantern as the vanilla lantern. Mana and Artifice might be doing something to specifically get the replaced vanilla lantern instead of getting it from the registry.
I think this issue should be reported to them, since it depends on how they obtain a reference to the lantern.

**Comment by SuperMartijn642** [comment]
Closing due to no response and since I believe the issue lies with the other mod.
