### ISSUE TITLE
[Bug] Additional Lanterns make Supplementaries's Wall Lantern not drop item when broke

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [SuperMartijn642/AdditionalLanterns#22]
**Version Info**
- Minecraft, 1.19.2
- Additional Lantern, 1.0.4a-fabric-mc1.19.2
- SuperMartijn642's Core lib, 1.1.9d-fabric-mc1.19.2

**Description of the Bug**
When you install both Supplementaries and Additional Lanterns, and you break a wall lantern, it will not drop the lantern. However, if you break a lantern that placed on the ground or hanging under the ceiling, the lantern will drop.
Only the vanilla lantern has this bug, other lanterns such as soul lantern or from any other mods don't have this problem
If you place the wall lantern first, and then install Additional Lanterns, that wall lantern still drop the item.

**Steps to Reproduce**
1) Place the lantern (only the default version) on the wall
2) Break it with a pickaxe
3) Nothing drops

**Screenshots**
https://github.com/SuperMartijn642/AdditionalLanterns/assets/111768452/d464ac87-e6e9-4c54-815b-72c0678af867

**Comment by SuperMartijn642** [comment]
Turns out it was just the normal lantern block itself that had an invalid loot table, nothing to with Supplementaries. In the cases where it is possible (i.e. not toggled by right clicking and not powered by redstone), the vanilla lantern block is used, thus you still got a drop from the block. However, once you right-click it or power it, the additional lanterns block is used instead and it wouldn't drop anything :p

Anyways, it is fixed now in version 1.0.5 of Additional Lanterns.
Thank you for reporting the issue!
