### ISSUE TITLE
[Crash] mixin squared crash (compatibility with more culling)

### ISSUE THREAD

**Issue by VaporeonScripts** [SuperMartijn642/AdditionalLanterns#48]
**Version Info**
- Minecraft 1.21.1
- Additional Lantern latest possible
- SuperMartijn642's Core lib, latest possible

**Steps to Reproduce**
add both this mod and more culling

**Crash report (~/logs/latest.log)**
https://mclo.gs/Fo1mAqx

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/64d5b8cf-e903-434c-91ab-f37511cb100f)

**Comment by SuperMartijn642** [comment]
This seems to be caused by two MixinSquared versions being loaded with the different classes at the same location. From the logs, it seems `moreculling-neoforge-1.21.1-1.0.0-beta.1.jar` contains `mixinsquared-neoforge-0.2.0.jar`,  `mixinsquared-neoforge-0.2.0.jar` contains `MixinSquared-0.2.0.jar`, and `elytratrims-neoforge-3.5.3 1.21.jar` contains `mixinsquared-neoforge-0.1.2-beta.4.jar`.
I'd suggest reporting it to MixinSquared or the mods containing it.

Anyways, this has nothing to do with Additional Lanterns and will happen for any mod installed alongside the ones mentioned above.

**Comment by VaporeonScripts** [comment]
Thing is I got no mod named mixins squared xd,but ig I will report it to elytra trims
