### ISSUE TITLE
[Bug] Vanilla Minecraft Lanterns change their tag to Additional Lanterns when placed in the world.

### ISSUE THREAD

**Issue by kedamono** [SuperMartijn642/AdditionalLanterns#9]
**Version Info**
- Minecraft, 1.19.2
- Additional Lantern, 1.0.1a-forge-mc1.19
- SuperMartijn642's Core lib, 1.0.1a-forge-mc1.19

**Description of the Bug**
When I place a vanilla Minecraft lantern, it changes from Minecraft to Additional Lanterns as the source. This is a problem with other mods that look for the vanilla version of the lantern and don't recognize the ones tagged as "Additional Lanterns"

**Steps to Reproduce**
1. Craft a vanilla Minecraft lantern.
2. Check to see that it's tagged as "Minecraft" in your inventory.
3. Place the lantern on a block.
4. The lantern is now tagged as "Additional Lanterns"

**Screenshots**

![2022-12-29_13 56 27](https://user-images.githubusercontent.com/23420636/209997841-0e29ac52-c787-4056-9b65-d10a98b009b0.png)

**Comment by Talyda** [comment]
Just adding a "+1" to this report.
I made a vanilla lantern, because I need a vanilla lantern to be placed, but once it is placed, it turns into a nto vanilla lantern, and it causing them to be removed, and making a real headache!

**Comment by SuperMartijn642** [comment]
Additional Lanterns replaces the vanilla lantern item with an item that places a custom lantern block added by Additional Lanterns. Additional Lanterns does not overwrite the vanilla lantern block, thus, indeed, the item will be registered under `minecraft:lantern`, but the block it places will be `additionallanterns:normal_lantern`.

I have now made it so that in cases where the custom lantern block is not powered by redstone and not toggle off (and not waterlogged for 1.14 and 1.15), it will simply use the vanilla lantern block instead. This should make it compatible with any other mods looking for the vanilla lantern block.

It is available in Additional Lanterns 1.0.3.
Thank you for reporting the issue!
